### ISSUE TITLE
Cleaning out topics

### ISSUE THREAD

**Issue by greeven** [kfleischmann/geekhub#4]
A documented command about how to clean out topics would be nice.

It get's messy at some point.

**Comment by kfleischmann** [comment]
Fair point. No. Actually it is only able to create a new one. :/

Am 05.10.2018 12:29 schrieb "greeven" <notifications@github.com>:

A documented command about how to clean out topics would be nice.

It get's messy at some point.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kfleischmann/geekhub/issues/4>, or mute the thread

**Comment by greeven** [comment]
Awesome thx.

For others: it's `/geekup/kafka1/`. ;)

**Comment by kfleischmann** [comment]
fixed ;) thanks
